import type { Metadata } from "next";
import { AR_One_Sans, Plus_Jakarta_Sans, Righteous } from "next/font/google";
import "@/styles/globals.css";

const righteous = Righteous({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-righteous",
});

const ar_one_sans = AR_One_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ar_one_sans",
});

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-plus_jakarta_sans",
});

export const metadata: Metadata = {
  title: "ROS-Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${righteous.variable} ${ar_one_sans.variable} ${plus_jakarta_sans.variable}`}
    >
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
