export const bankAccounts = [
  {
    id: 1,
    bankName: "Wema Bank",
    accountNumber: "2000394859",
    accountName: "Boma Dave",
    isDefault: false,
  },
  {
    id: 2,
    bankName: "Kuda Bank",
    accountNumber: "3847383838383",
    accountName: "Boma Dave",
    isDefault: true,
  },
  {
    id: 3,
    bankName: "Access Bank",
    accountNumber: "0712984561",
    accountName: "Tolu Adetayo",
    isDefault: false,
  },
  {
    id: 4,
    bankName: "First Bank",
    accountNumber: "3110098776",
    accountName: "Emeka Obi",
    isDefault: false,
  },
  {
    id: 5,
    bankName: "GTBank",
    accountNumber: "0027483920",
    accountName: "Fatima Bello",
    isDefault: false,
  },
    {
    id: 6,
    bankName: "Wema Bank",
    accountNumber: "2000394859",
    accountName: "Boma Dave",
    isDefault: false,
  },
  {
    id: 7,
    bankName: "Kuda Bank",
    accountNumber: "3847383838383",
    accountName: "Boma Dave",
    isDefault: true,
  },
  {
    id: 8,
    bankName: "Access Bank",
    accountNumber: "0712984561",
    accountName: "Tolu Adetayo",
    isDefault: false,
  },
  {
    id: 9,
    bankName: "First Bank",
    accountNumber: "3110098776",
    accountName: "Emeka Obi",
    isDefault: false,
  },
  {
    id: 10,
    bankName: "GTBank",
    accountNumber: "0027483920",
    accountName: "Fatima Bello",
    isDefault: false,
  },
    {
    id: 11,
    bankName: "Wema Bank",
    accountNumber: "2000394859",
    accountName: "Boma Dave",
    isDefault: false,
  },
  {
    id: 12,
    bankName: "Kuda Bank",
    accountNumber: "3847383838383",
    accountName: "Boma Dave",
    isDefault: true,
  },
  {
    id: 13,
    bankName: "Access Bank",
    accountNumber: "0712984561",
    accountName: "Tolu Adetayo",
    isDefault: false,
  },
  {
    id: 14,
    bankName: "First Bank",
    accountNumber: "3110098776",
    accountName: "Emeka Obi",
    isDefault: false,
  },
  {
    id: 15,
    bankName: "GTBank",
    accountNumber: "0027483920",
    accountName: "Fatima Bello",
    isDefault: false,
  },
    {
    id: 16,
    bankName: "Wema Bank",
    accountNumber: "2000394859",
    accountName: "Boma Dave",
    isDefault: false,
  },
  {
    id: 17,
    bankName: "Kuda Bank",
    accountNumber: "3847383838383",
    accountName: "Boma Dave",
    isDefault: true,
  },
  {
    id: 18,
    bankName: "Access Bank",
    accountNumber: "0712984561",
    accountName: "Tolu Adetayo",
    isDefault: false,
  },
  {
    id: 19,
    bankName: "First Bank",
    accountNumber: "3110098776",
    accountName: "Emeka Obi",
    isDefault: false,
  },
  {
    id: 20,
    bankName: "GTBank",
    accountNumber: "0027483920",
    accountName: "Fatima Bello",
    isDefault: false,
  },
    {
    id: 21,
    bankName: "GTBank",
    accountNumber: "0027483920",
    accountName: "Fatima Bello",
    isDefault: false,
  },
    {
    id: 22,
    bankName: "Wema Bank",
    accountNumber: "2000394859",
    accountName: "Boma Dave",
    isDefault: false,
  },
  {
    id: 23,
    bankName: "Kuda Bank",
    accountNumber: "3847383838383",
    accountName: "Boma Dave",
    isDefault: true,
  },
  {
    id: 24,
    bankName: "Access Bank",
    accountNumber: "0712984561",
    accountName: "Tolu Adetayo",
    isDefault: false,
  },
  {
    id: 25,
    bankName: "First Bank",
    accountNumber: "3110098776",
    accountName: "Emeka Obi",
    isDefault: false,
  },
  {
    id: 26,
    bankName: "GTBank",
    accountNumber: "0027483920",
    accountName: "Fatima Bello",
    isDefault: false,
  },
  
];
